"""
uploader.py — YouTube Data API v3 upload via OAuth2
═══════════════════════════════════════════════════════════════════

Handles uploading rendered CinemaForge projects to YouTube.
Supports both long-form and Shorts formats.
Uses context-aware tag extraction from the production script.
═══════════════════════════════════════════════════════════════════
"""

import os
import re
import logging
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload
from google.oauth2.credentials import Credentials
from google.auth.transport.requests import Request
from google_auth_oauthlib.flow import InstalledAppFlow
from dotenv import load_dotenv

load_dotenv()

log = logging.getLogger("uploader")

SCOPES = [
    "https://www.googleapis.com/auth/youtube.upload",
    "https://www.googleapis.com/auth/youtube.readonly",
]

CLIENT_SECRET_FILE = os.environ.get("YT_CLIENT_SECRET", "client_secret.json")
TOKEN_FILE         = os.environ.get("YT_TOKEN_FILE",     "data/yt_token.json")

YT_CATEGORY_ID     = os.environ.get("YT_CATEGORY_ID", "22")   # 22 = People & Blogs
YT_PRIVACY         = os.environ.get("YT_PRIVACY",     "public")
YT_TITLE_LIMIT     = 100   # YouTube hard limit

# ── Fallback global tags if script yields nothing ────────────────────────────
_FALLBACK_TAGS = [
    "cinemaforge", "ai", "storytelling", "videoediting", "contentcreation",
]

# ── Keyword → tag mapping (order matters: first match wins priority) ─────────
_KEYWORD_TAGS: list[tuple[str, str]] = [
    (r"history|historical|ancient", "history"),
    (r"crime|true crime|detective", "truecrime"),
    (r"horror|scary|spooky", "horror"),
    (r"tech|technology|future", "technology"),
    (r"nature|animals|wildlife", "nature"),
    (r"business|finance|money", "business"),
    (r"health|fitness|workout", "health"),
    (r"travel|adventure|explore", "travel"),
    (r"motivation|success|growth", "motivation"),
    (r"philosophy|wisdom|stoic", "philosophy"),
    (r".", "cinemaforge"),
    (r".", "aivideo"),
]


def extract_tags_from_script(script: str, max_tags: int = 10) -> list[str]:
    """Analyse the script text and return contextually relevant tags."""
    text  = script.lower()
    seen  = set()
    tags  = []
    for pattern, tag in _KEYWORD_TAGS:
        if tag in seen:
            continue
        if re.search(pattern, text):
            seen.add(tag)
            tags.append(tag)
        if len(tags) >= max_tags:
            break
    
    if len(tags) < 3:
        for fb in _FALLBACK_TAGS:
            if fb not in seen:
                tags.append(fb)
                seen.add(fb)
            if len(tags) >= max_tags:
                break
    return tags


def build_yt_metadata(project_name: str, script: str, is_short: bool = False) -> tuple[str, str, list[str]]:
    """Build YouTube title, description, and tag list."""
    tags = extract_tags_from_script(script)
    title = project_name.replace("_", " ").strip().title()
    
    if is_short:
        # For shorts, add #Shorts and some tags to the title
        title_with_tags = f"{title} #Shorts"
        for tag in tags:
            candidate = f"{title_with_tags} #{tag}"
            if len(candidate) <= YT_TITLE_LIMIT:
                title_with_tags = candidate
            else:
                break
        title = title_with_tags

    description = f"Generated by CinemaForge.\n\n"
    description += " ".join(f"#{t}" for t in tags)
    if is_short:
        description += " #Shorts"

    return title, description, tags


def _get_credentials() -> Credentials:
    creds = None
    if os.path.exists(TOKEN_FILE):
        creds = Credentials.from_authorized_user_file(TOKEN_FILE, SCOPES)
    
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            # Note: In a headless server, this will fail unless token.json is already there
            if not os.path.exists(CLIENT_SECRET_FILE):
                raise FileNotFoundError(f"YouTube credentials missing: {CLIENT_SECRET_FILE} not found.")
            flow = InstalledAppFlow.from_client_secrets_file(CLIENT_SECRET_FILE, SCOPES)
            creds = flow.run_local_server(port=8090)
            
        os.makedirs(os.path.dirname(TOKEN_FILE) or ".", exist_ok=True)
        with open(TOKEN_FILE, "w") as f:
            f.write(creds.to_json())
    return creds


def upload_video(video_path: str, title: str, description: str, tags: list[str]) -> str:
    """Uploads video to YouTube. Returns the YouTube video ID."""
    if not os.path.exists(video_path):
        raise FileNotFoundError(f"Video file not found: {video_path}")

    log.info(f"[upload] Starting upload: {title!r}")
    creds   = _get_credentials()
    youtube = build("youtube", "v3", credentials=creds)

    body = {
        "snippet": {
            "title":       title[:YT_TITLE_LIMIT],
            "description": description,
            "tags":        tags,
            "categoryId":  YT_CATEGORY_ID,
        },
        "status": {
            "privacyStatus": YT_PRIVACY,
            "selfDeclaredMadeForKids": False,
        },
    }

    media   = MediaFileUpload(video_path, mimetype="video/mp4", resumable=True)
    request = youtube.videos().insert(
        part=",".join(body.keys()),
        body=body,
        media_body=media,
    )

    response = None
    while response is None:
        status, response = request.next_chunk()
        if status:
            log.info(f"[upload] Progress: {int(status.progress() * 100)}%")

    video_id = response["id"]
    log.info(f"[upload] Done: https://youtu.be/{video_id}")
    return video_id
